name: Terraform Plan

on:
  pull_request:
    branches:
      - master
    paths:
      - env/staging/**

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: [./env/staging]
    env:
      tf_version: "1.0.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: cd ./${{ matrix.workdir }} && terraform init

      - name: Terraform Validate
        run: cd ./${{ matrix.workdir }} && terraform validate -no-color
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: cd ./${{ matrix.workdir }} && terraform plan -no-color
        continue-on-error: true
